# Problem 1 

In [13]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
ray = np.array([32,45,67,89,12])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print(np.sort(ray))

[12 32 45 67 89]


# Problem 2

In [14]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayilar = np.array([10,15,30,45,60])
print(sayilar)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayilar2 = np.arange(5,15)
print(sayilar2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayilar3 = np.arange(50,100,5)
print(sayilar3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayilar4 = np.zeros(10)
print(sayilar4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayilar5 = np.ones(10)
print(sayilar5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayilar6 = np.linspace(0,100,5)
print(sayilar6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random_numbers = np.random.randint(10,31, size=5)
print(random_numbers)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random_numbers2 = np.random.uniform(-1, 1, size=10)
print(random_numbers2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random_numbers3 = np.random.randint(10,50, size=(3,5))
print(random_numbers3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random_numbers3.sum(axis=0))
print(random_numbers3.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random_numbers3.max())
print(random_numbers3.min())
print(random_numbers3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random_numbers3.argmax())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random_numbers4 = np.random.randint(10, 20, size=8)
print(random_numbers4[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random_numbers4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random_numbers3[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random_numbers3[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random_numbers3[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(random_numbers3**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5 = np.random.randint(-50, 50, size=(3,5))
print((random_numbers5 > 0) & (random_numbers5 % 2 == 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[10 20 22 22 16]
[ 0.08952388  0.95583108 -0.72166027 -0.68481075  0.42355049 -0.68929022
  0.66266728  0.45720376  0.35537857  0.9081307 ]
[[46 32 17 13 15]
 [38 15 24 29 29]
 [36 35 44 42 14]]
[120  82  85  84  58]
[123 135 171]
46
13
28.6
0
[14 13 16]
[13 14 17 12 14 16 13 14]
[46 32 17 13 15]
24
[46 38 36]
[[2116 1024  289  169  225]
 [1444  225  576  841  841]
 [1296 1225 1936 1764  196]]
[[ True False False False False]
 [False False False False False]
 [False False  True False False]]
