# Problem 1

In [24]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.linspace(0,10,5)
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
matris = np.array([ 0, 2.5, 5., 7.5, 10., 12.5])
yeni = matris.reshape(3,2)
print(yeni)
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)


[ 0.   2.5  5.   7.5 10. ]
(5,)
[[ 0.   2.5]
 [ 5.   7.5]
 [10.  12.5]]
1


# Problem 2

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [21]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
a = np.arange(1,10,2)
print(a)
# 2 - Oluşturduğunuz matrisi parçalayın
print(np.split(a,[2,4]))
b = np.split(a,[2,4])
# 3 - Parçalanmış matrisleri birleştirin
x = np.array([1,3])
y = np.array([5,7])
z= np.array([9])
print(np.concatenate([x,y,z]))


[1 3 5 7 9]
[array([1, 3]), array([5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [24]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
x = np.random.randint(5,100,10)
print(x)
# 2 - matris'in özelliklerini inceleyin
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)


[84 51 14  8 20 41 64 84 94 80]
1
(10,)
10
int32
